COMMON_MODULES = sonar servo radio uart # this must come BEFORE the common.mk inclusion
include ../common/common.mk

#OBJECTS += something.o
#something.o: something.h something_else.h
#something.h: foo.h
