#! /bin/bash

if [ $# -ne 1 ]; then
    echo "usage: scripts/create-project project_name"
    exit 1
fi

if [ ! -d common ]; then
    echo "ERROR: projects must be created in the same directory as the common directory"
    exit 1
fi

PROJECT_NAME=$1

# check that project name matches the regex /^[a-z][a-z0-9_]*$/
if [ ! `echo $PROJECT_NAME | sed -n -e '/^[a-z][a-z0-9_]*$/p'` ]; then
    echo "ERROR: project names must start with a lowercase letter, and can only"
    echo "       contain lowercase letters, numbers, and underscores"
    exit 1
fi

if [ -a $PROJECT_NAME ]; then
    echo "ERROR: $PROJECT_NAME already exists"
    exit 1
fi

mkdir $PROJECT_NAME
cp scripts/_create-project/makefile $PROJECT_NAME
cp scripts/_create-project/template.c $PROJECT_NAME/$PROJECT_NAME.c
sed "s/__project_name/$PROJECT_NAME/g" scripts/_create-project/template.aps > $PROJECT_NAME/andrew_$PROJECT_NAME.aps
cp $PROJECT_NAME/{andrew,eric}_$PROJECT_NAME.aps
